### ISSUE TITLE
Generate a libraries.json file to view/public/

### ISSUE THREAD

**Issue by rgb-one** [cornelius/inqlude#101]
...which would have the manifest data for all the libraries on inqlude. This would make the libraries.json file the data source from which search terms are compared.

**Comment by cornelius** [comment]
We already have a file like that. See the [documentation](https://github.com/cornelius/inqlude/blob/master/accessing-inqlude-data.md#all-data-in-one-json). Does that meet what you were thinking of or would we need anything else?

**Comment by rgb-one** [comment]
Thats exactly what I was thinking of, thanks.
