### ISSUE TITLE
Align summaries on development page vertically

### ISSUE THREAD

**Issue by cornelius** [cornelius/inqlude#19]
On the development versions page (http://inqlude.org/development.html) the summaries of the libraries are only vertically aligned within each section, but not across sections. This should be fixed to make the page look more balanced.

**Comment by InsaneNaman** [comment]
Sir , I want to solve this but can you please tell me something more about this issue :)

**Comment by cornelius** [comment]
Please check out, if this still applies in the new layout. You can locally render it with the `inqlude view` command by providing a parameter `--templates=two-column`.

**Comment by cornelius** [comment]
Fixed in new layout, which is now the default.
