### ISSUE TITLE
Show latest releases on web page

### ISSUE THREAD

**Issue by cornelius** [cornelius/inqlude#22]
It would be nice to have a section with latest releases on the web page, so you know which libraries have been recently updated.

**Comment by nanduni-nin** [comment]
@cornelius I already thought of including this idea in my proposal for GSoC Project: **Improve categorization and search on Inqlude web site**. I suppose that I need to look into manifest files in inqlude-data repository that contains library meta data of Qt based libraries. Am I right?

**Comment by cornelius** [comment]
@nanduni-nin The release date is part of the data in the manifest. So generating a list of all libraries which have been updated should be quite easy. The main challenge (similar as with #26 and #27) is to come up with a good design how to integrate that into the web site.
