### ISSUE TITLE
Extend the platforms set

### ISSUE THREAD

**Issue by staniek** [cornelius/inqlude#24]
Hi Cornelius,
I propose to extend the platforms set.
https://github.com/cornelius/inqlude/blob/master/manifest-format.md#platforms
E.g. qtwebsockets.manifest lists:
  "platforms": [
    "Linux",
    "OS X",
    "Windows",
    "Android",
    "iOS"
  ]

Would you think all that's supported by Qt would be OK?
Also, do we have to use OS X or Mac? How about some clarity and autovalidation here? :)

**Comment by cornelius** [comment]
Yes, there already is an issue for that: #18.

It should be "OS X". The current manifests don't do this consistently, though.

All that's supported by Qt sounds right. Is there a definitive list of this somewhere?

**Comment by staniek** [comment]
Hi Cornelius,
http://doc.qt.io/QtSupportedPlatforms and http://doc.qt.io/qt-5/supported-platforms.html

**Comment by cornelius** [comment]
Ok, looks like your list already covers the platforms which are used most of the time. So let's expand the current list by "Android" and "iOS" and get the values checked. I'll close this issue now and track progress in #18.
