### ISSUE TITLE
Tag support

### ISSUE THREAD

**Issue by rgb-one** [cornelius/inqlude#30]
Tagging can be a useful way of grouping/categorizing libraries. A defined set of tags can be established, to limit the amount of possible tag entries (for easier management).

**Comment by cornelius** [comment]
What tags do you have in mind? There already is quite a bit of data to classify the libraries and the total number is not so large that a huge number of tags would be needed.

**Comment by cornelius** [comment]
We'll address that through the topics we are introducing as part of the new layout. (See `two-columns` templates).

**Comment by cornelius** [comment]
Done, released and published on https://inqlude.org.
