### ISSUE TITLE
Issues of two-column layout

### ISSUE THREAD

**Issue by cornelius** [cornelius/inqlude#69]
Here are a few small issues I noticed with the two-column layout:
- [x] The latest releases aren't sorted correctly. KDE Frameworks comes last, although it's the newest. Newest should be on top
- [x] The grey boxes behind the sections on the left sidebar might be a bit distracting. Have you tried to render the sidebar without boxes, just using titles and some space?
- [x] Is the font different or smaller than in the one-column layout. It appears to be a bit smaller than in the current web site. This makes it a bit harder to read in my opinion.
- [x] Limereport has a weird two-column box layout in the description. This also seems to happen in the one-column layout, but still something we should look into.
- [x] It would be nice to have an "All" topic at the top of the topics list which goes to the complete list with all libraries.
- [x] Why are there no libraries in the "Artwork" topic. Didn't we have a few libraries there?
- [ ] I would put the "last updated" text on the same line as the "Inqlude is a KDE project" text. It also should only be on the home page, not on any of the other pages.
- [x] The Inqlude logo should link back to the home page

**Comment by nanduni-nin** [comment]
It seems that we cannot find any library listed for 'Artwork' topic at git://anongit.kde.org/websites/inqlude-data. They have been removed by some way, I am not sure why. The topics are not available for most of the latest manifests of the libraries right now.

**Comment by nanduni-nin** [comment]
I suppose that LimeReport's weird behavior of description might be due to '|' symbol in its description.

**Comment by cornelius** [comment]
The topics for the KDE Frameworks are not shown in the latest manifests, because they are automatically created with each new release of the frameworks using the two related sub commands. They don't know how to handle topics yet. This needs to be addressed separately. I would suggest to preserve topics from the generic manifests. I have opened a new issue for that: #71.

**Comment by cornelius** [comment]
The variant without the boxes in the sidebar is interesting. Somehow it still doesn't feel balanced. Maybe one background box for the whole column instead of one per section would be good?

**Comment by cornelius** [comment]
The "last updated" issue doesn't seem to be addressed yet.

**Comment by nanduni-nin** [comment]
I came across few problems to address the "last updated" issue. Few concerns here are,
* We need to make the text "Inqlude is a KDE project" to be available on every page, centered at the bottom of the page. This means that we need to add it to `layout.html.haml` file.
* We need  "last updated" text to appear only in `index.html.haml` file.
* Since those two texts are in two files, it seems difficult to make those two texts  "last updated" and "Inqlude is a KDE project" appear on the same line.
* One thing we could do is to add the text "Inqlude is a KDE project"  to each and every `.html.haml` file excluding `layout.html.haml`, and "last updated" text to only `index.html.haml` file. Would that be a good solution?
* There are less documentations on HAML, I looked into many, but found no way to do that.

**Comment by cornelius** [comment]
You could use a helper in the layout which inserts the updated message into the footer. Than when rendering the template the helper could either return the message or an empty string, when not rendering the home page. So this would be an additional method in the View class, which is then called from the layout template.

**Comment by nanduni-nin** [comment]
Thank you. I will try that way

**Comment by nanduni-nin** [comment]
I added this part to `view.rb`.
```
def add_footer text
    out = "Inqlude is a "
    out += link_to "KDE project", "http://kde.org"
    out += "|"
    out += link_to "Legal", "http://www.kde.org/community/whatiskde/impressum.php"
    out += "<span class='footer'>"
    out += text
    out += "</span>"
    out
  end
```
Then I want to call that from `layout.html.haml` file. I am stuck in finding some way to specifically refer the `index.html.haml` file.

```
- if <**How should I refer index.html.haml**>
    - text = 'Last updated on ' + Date.today.to_s
- else
    - text = ""
= add_footer text
```
Any suggestion is highly appreciated.

**Comment by cornelius** [comment]
I would not put the `if` into the HAML template, but in the `View` class. There you know which template is rendered and can return either the "last updated" text or an empty string.
