### ISSUE TITLE
libqemf

### ISSUE THREAD

**Issue by iondevsrl** [cornelius/inqlude#95]
Hi,

I would like to submit a library for inclusion into your archive. Since I'm not very sure how to proceed, I'll simply attach a manifest file that I have created for this lib.

Thanks in advance for your answer.

Kind regards,
Ion

[libqemf.manifest.zip](https://github.com/cornelius/inqlude/files/1491634/libqemf.manifest.zip)

**Comment by cornelius** [comment]
Could you please provide the manifest as pull request on the inqlude-data repo at https://github.com/cornelius/inqlude-data ?
